### ISSUE TITLE
No 'model_MNIST2.t7' ?

### ISSUE THREAD

**Issue by wanghuok** [brcsomnath/Advanced-GAP#1]
Hello, thanks for your code. Is this project do not include 'model_MNIST2.t7', and where can i get it. Thanks.

**Comment by arnaghosh** [comment]
Hi @wanghuok 
Thanks for your interest in our project. Sorry for the incomplete documentation on how to run the code and reproduce the results. We are actually still developing on this project and will soon be updating that. 
The model file you are looking for is generated by the "mnist.lua" file. So, you need to run the file first to get the model file and then use GAP to obtain further results.
Let us know if you have some other questions.
Cheers
